import React from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Banknote,
  Bell,
  Bookmark,
  Calculator,
  Calendar,
  Camera,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  CircleDollarSign,
  Clock,
  Database,
  DollarSign,
  Download,
  Edit,
  FastForward,
  Flag,
  Gift,
  GitCompare,
  Globe,
  Gauge,
  GripVertical,
  History,
  Home,
  Info,
  Languages,
  Leaf,
  Link,
  Lock,
  Mail,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  Navigation,
  Package,
  Pause,
  PiggyBank,
  Play,
  Plus,
  Rocket,
  RotateCcw,
  RotateCw,
  Search,
  Settings,
  Share,
  Shield,
  ShieldCheck,
  Signpost,
  SkipBack,
  SkipForward,
  Snail,
  Square,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Target,
  Tag,
  Trash,
  TrendingUp,
  TrendingDown,
  Trophy,
  Truck,
  Undo2,
  Redo2,
  Upload,
  User,
  Wand,
  Zap,
  X,
  Droplet,
  Eye,
  EyeOff,
  Filter,
  Smartphone,
  ChevronDown,
  Heart,
  Phone,
  Slash,
  Repeat,
  RefreshCw,
  Replace,
  Save,
  Scale,
  BarChart3,
  Copy,
  CheckCircle,
  HelpCircle,
  Loader,
  Diff,
} from 'lucide-react';

// Complete icon map for semantic naming
const iconMap = {
  // Navigation
  'home': Home,
  'menu': Menu,
  'back': ArrowLeft,
  'forward': ArrowRight,
  'next': ChevronRight,
  'previous': ChevronLeft,
  'up': ArrowUp,
  'down': ArrowDown,
  'chevron-down': ChevronDown,
  'first': ChevronsLeft,
  'last': ChevronsRight,
  'start': SkipBack,
  'end': SkipForward,

  // Common Actions
  'add': Plus,
  'create': Plus,
  'new': Plus,
  'remove': Minus,
  'delete': Trash,
  'edit': Edit,
  'update': Edit,
  'modify': Edit,
  'save': Save,
  'undo': Undo2,
  'redo': Redo2,
  'search': Search,
  'filter': Filter,
  'sort': GripVertical,
  'copy': Copy,
  'close': X,
  'exit': X,
  'dismiss': X,

  // Communication
  'message': MessageCircle,
  'chat': MessageCircle,
  'email': Mail,
  'phone': Phone,
  'notification': Bell,
  'bell': Bell,
  'alert': Bell,
  'info': Info,
  'help': HelpCircle,

  // Media
  'upload': Upload,
  'download': Download,
  'image': Monitor,
  'camera': Camera,
  'video': Monitor,
  'link': Link,

  // User
  'user': User,
  'account': User,
  'profile': User,
  'person': User,
  'people': User,

  // Status/State
  'active': Activity,
  'inactive': Circle,
  'success': CheckCircle,
  'error': AlertCircle,
  'warning': AlertTriangle,
  'loading': Loader,

  // Environment
  'leaf': Leaf,
  'tree': Leaf,
  'plant': Leaf,
  'water': Droplet,
  'drop': Droplet,
  'trash': Trash,
  'package': Package,
  'recycle': Repeat,

  // Location
  'location': MapPin,
  'mapPin': MapPin,
  'pin': MapPin,
  'map': Navigation,
  'globe': Globe,

  // Time
  'calendar': Calendar,
  'clock': Clock,
  'time': Clock,
  'history': History,

  // Settings
  'settings': Settings,
  'gear': Settings,
  'config': Settings,

  // Social
  'share': Share,
  'social': Share,

  // Points/Rewards
  'star': Star,
  'trophy': Trophy,
  'medal': Medal,
  'badge': BadgeCheck,
  'gift': Gift,
  'reward': Gift,

  // Finance
  'money': Banknote,
  'cash': Banknote,
  'wallet': PiggyBank,
  'coin': CircleDollarSign,
  'price': Tag,
  'cost': Calculator,
  'budget': PiggyBank,
  'currency': DollarSign,
  'invest': TrendingUp,
  'profit': TrendingUp,
  'growth': TrendingUp,
  'increase': ArrowUp,
  'decrease': ArrowDown,
  'rise': ArrowUp,
  'fall': ArrowDown,
  'left': ArrowLeft,
  'right': ArrowRight,
  'finance': TrendingUp,

  // Analytics
  'chart': BarChart3,
  'graph': BarChart3,
  'analytics': BarChart3,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,

  // Organization
  'folder': Monitor,
  'file': Monitor,
  'document': Monitor,
  'database': Database,
  'server': Database,
  'store': Database,
  'keep': Archive,
  'archive': Archive,
  'backup': Database,

  // Lock/Security
  'lock': Lock,
  'unlock': Lock,
  'protected': Shield,
  'secure': ShieldCheck,
  'protect': Shield,
  'guard': Shield,
  'defend': Shield,
  'safe': ShieldCheck,
  'danger': AlertCircle,

  // Additional
  'eye': Eye,
  'eye-off': EyeOff,
  'heart': Heart,
  'cycle': Repeat,
  'loop': Repeat,
  'refresh': RefreshCw,
  'reload': RefreshCw,
  'sync': RefreshCw,
  'synchronize': RefreshCw,
  'more': MoreVertical,
  'kebab': MoreVertical,
  'play': Play,
  'pause': Pause,
  'stop': Square,
  'forward-2': FastForward,
  'rewind': RotateCcw,
  'slow': Snail,
  'fast': Zap,
  'speed': Gauge,
  'quick': Zap,
  'instant': Zap,
  'immediate': Zap,
  'now': Clock,
  'today': Calendar,
  'tomorrow': Sunrise,
  'yesterday': Sunset,
  'future': Rocket,
  'past': History,
  'present': Gift,
  'current': Target,
  'restore': RotateCcw,
  'reverse': RotateCcw,
  'replay': RotateCcw,
  'repeat': Repeat,
  'match': CheckCircle,
  'compare': GitCompare,
  'diff': Diff,
  'change': Replace,
  'transform': Wand,
  'convert': Repeat,
  'translate': Languages,
  'language': Languages,
  'locale': Globe,
  'region': Globe,
  'country': Flag,
  'flag': Flag,
  'banner': Flag,
  'sign': Signpost,
  'label': Tag,
  'tag': Tag,
  'notify': Bell,
  'remind': Clock,
  'remember': Bookmark,
  'caution': AlertTriangle,
  'resume': Play,
  'moon': Moon,
  'sun': Sun,
  'truck': Truck,
};

const Icon = ({ name, size = 24, className = '', ariaHidden = false, title }) => {
  const IconComponent = name && iconMap[name] ? iconMap[name] : Circle;
  
  return (
    <IconComponent
      size={size}
      className={className}
      aria-hidden={ariaHidden}
      title={title}
      {...(ariaHidden === false && title && { 'aria-label': title })}
    />
  );
};

export default Icon;
